(ns mario.style.desktop.sprites
  (:require [garden.units :refer [px]]))

(defn export []
  [[:.sprite {:background-image "url(../img/css-sprites.png)"
              :background-repeat "none"}
    [:&:.sprite-above-ground-thumb {:background-position [[0 0]] :width (px 40) :height (px 40)}]
    [:&:.sprite-athletic-thumb {:background-position [[0 (px -90)]] :width (px 40) :height (px 40)}]
    [:&:.sprite-baby-yoshi {:background-position [[0 (px -180)]] :width (px 32) :height (px 42)}]
    [:&:.sprite-blue-koopa-kick {:background-position [[0 (px -272)]] :width (px 32) :height (px 41)}]
    [:&:.sprite-blue-yoshi {:background-position [[0 (px -363)]] :width (px 64) :height (px 64)}]
    [:&:.sprite-bullet-bill {:background-position [[0 (px -477)]] :width (px 32) :height (px 28)}]
    [:&:.sprite-chargin-chuck {:background-position [[0 (px -555)]] :width (px 48) :height (px 44)}]
    [:&:.sprite-coin-snake {:background-position [[0 (px -649)]] :width (px 32) :height (px 82)}]
    [:&:.sprite-dino-rhino {:background-position [[0 (px -781)]] :width (px 65) :height (px 64)}]
    [:&:.sprite-evil-king-koopa-thumb {:background-position [[0 (px -895)]] :width (px 40) :height (px 40)}]
    [:&:.sprite-feather {:background-position [[0 (px -985)]] :width (px 32) :height (px 32)}]
    [:&:.sprite-fire-flower {:background-position [[0 (px -1067)]] :width (px 32) :height (px 34)}]
    [:&:.sprite-fishing-lakitu {:background-position [[0 (px -1151)]] :width (px 78) :height (px 90)}]
    [:&:.sprite-flying-koopa {:background-position [[0 (px -1291)]] :width (px 60) :height (px 55)}]
    [:&:.sprite-flying-piranha-plant {:background-position [[0 (px -1396)]] :width (px 32) :height (px 40)}]
    [:&:.sprite-flying-yoshi {:background-position [[0 (px -1486)]] :width (px 58) :height (px 78)}]
    [:&:.sprite-galoomba {:background-position [[0 (px -1614)]] :width (px 32) :height (px 32)}]
    [:&:.sprite-ghost-house {:background-position [[0 (px -1696)]] :width (px 40) :height (px 42)}]
    [:&:.sprite-jump-block {:background-position [[0 (px -1788)]] :width (px 32) :height (px 32)}]
    [:&:.sprite-kamikaze-koopa {:background-position [[0 (px -1870)]] :width (px 32) :height (px 41)}]
    [:&:.sprite-koopa-on-fence {:background-position [[(px -128) 0]] :width (px 37) :height (px 66)}]
    [:&:.sprite-koopa {:background-position [[(px -128) (px -116)]] :width (px 32) :height (px 54)}]
    [:&:.sprite-mad-wiggler {:background-position [[(px -128) (px -220)]] :width (px 65) :height (px 52)}]
    [:&:.sprite-magikoopa {:background-position [[(px -128) (px -322)]] :width (px 48) :height (px 60)}]
    [:&:.sprite-mario-die {:background-position [[(px -128) (px -432)]] :width (px 64) :height (px 96)}]
    [:&:.sprite-mario-on-yoshi {:background-position [[(px -128) (px -578)]] :width (px 50) :height (px 76)}]
    [:&:.sprite-mask-koopa {:background-position [[(px -128) (px -704)]] :width (px 32) :height (px 46)}]
    [:&:.sprite-mushroom-item {:background-position [[(px -128) (px -800)]] :width (px 32) :height (px 32)}]
    [:&:.sprite-p-block {:background-position [[(px -128) (px -882)]] :width (px 32) :height (px 32)}]
    [:&:.sprite-para-koopa {:background-position [[(px -128) (px -964)]] :width (px 34) :height (px 54)}]
    [:&:.sprite-para-mask-koopa {:background-position [[(px -128) (px -1068)]] :width (px 34) :height (px 48)}]
    [:&:.sprite-pidgit-bill {:background-position [[(px -128) (px -1166)]] :width (px 32) :height (px 32)}]
    [:&:.sprite-pipe {:background-position [[(px -128) (px -1248)]] :width (px 30) :height (px 34)}]
    [:&:.sprite-pumpkin-plant {:background-position [[(px -128) (px -1332)]] :width (px 36) :height (px 46)}]
    [:&:.sprite-question-block {:background-position [[(px -128) (px -1428)]] :width (px 32) :height (px 32)}]
    [:&:.sprite-red-koopa {:background-position [[(px -128) (px -1510)]] :width (px 32) :height (px 54)}]
    [:&:.sprite-red-yoshi {:background-position [[(px -128) (px -1614)]] :width (px 64) :height (px 64)}]
    [:&:.sprite-rex {:background-position [[(px -128) (px -1728)]] :width (px 38) :height (px 62)}]
    [:&:.sprite-rip-van-fish {:background-position [[(px -128) (px -1840)]] :width (px 32) :height (px 57)}]
    [:&:.sprite-silver-pblock-item {:background-position [[(px -128) (px -1947)]] :width (px 32) :height (px 32)}]
    [:&:.sprite-special-thumb {:background-position [[(px -256) 0]] :width (px 40) :height (px 40)}]
    [:&:.sprite-sumo-bros {:background-position [[(px -256) (px -90)]] :width (px 54) :height (px 45)}]
    [:&:.sprite-swimming-thumb {:background-position [[(px -256) (px -185)]] :width (px 40) :height (px 40)}]
    [:&:.sprite-torpedo-ted {:background-position [[(px -256) (px -275)]] :width (px 64) :height (px 11)} ]
    [:&:.sprite-under-ground-thumb {:background-position [[(px -256) (px -437)]] :width (px 40) :height (px 40)}]
    [:&:.sprite-wendy {:background-position [[(px -256) (px -527)]] :width (px 64) :height (px 52)}]
    [:&:.sprite-wiggler {:background-position [[(px -256) (px -629)]] :width (px 65) :height (px 52)}]
    [:&:.sprite-yellow-yoshi {:background-position [[(px -256) (px -731)]] :width (px 64) :height (px 64)}]
    [:&:.sprite-yoshi-eat-kamikaze-shell {:background-position [[(px -256) (px -845)]] :width (px 88) :height (px 54)}]
    [:&:.sprite-yoshi-house {:background-position [[(px -256) (px -949)]] :width (px 32) :height (px 30)}]
    [:&:.sprite-yoshi {:background-position [[(px -256) (px -1029)]] :width (px 64) :height (px 64)}]]])
